{
 "title": "Panel examples",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "ESXi host",
    "query": "SHOW TAG VALUES WITH KEY = \"esxhostname\""
   },
   {
    "name": "vm",
    "label": "VM",
    "query": "SHOW TAG VALUES WITH KEY = \"vmname\" WHERE \"esxhostname\" =~ /$host/"
   },
   { "name": "time", "label": "Time", "query": "20s,1m,5m,1h,12h,1d" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "content": "\n# Intro\n\nThis dashboard consists of examples used in a series of blog posts on how to build dashboards with VMware vSphere Performance data.\n\nThe datasource is an InfluxDB database with metrics pulled by the vSphere input plugin for the Telegraf agent.\n\nFor more information check out the [blog series](https://rudimartinsen.com/vsphere-performance-vol2)\n\n\n\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Graph panel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MEM Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "MEM Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "clustername", "operator": "=", "value": "vsan-01" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Stat panel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MEM Usage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "CPU - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage" ], "type": "alias" }
        ],
        [
         { "params": [ "latency_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "latency" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "MEM - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 20, "w": 6, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage" ], "type": "alias" }
        ],
        [
         { "params": [ "latency_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "latency" ], "type": "alias" }
        ],
        [
         { "params": [ "readiness_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "readiness" ], "type": "alias" }
        ],
        [
         { "params": [ "usagemhz_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage_mhz" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage" ], "type": "alias" }
        ],
        [
         { "params": [ "latency_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "latency" ], "type": "alias" }
        ],
        [
         { "params": [ "active_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "active" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage" ], "type": "alias" }
        ],
        [
         { "params": [ "latency_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "latency" ], "type": "alias" }
        ],
        [
         { "params": [ "readiness_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "readiness" ], "type": "alias" }
        ],
        [
         { "params": [ "usagemhz_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage_mhz" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_esxhostname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage" ], "type": "alias" }
        ],
        [
         { "params": [ "latency_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "latency" ], "type": "alias" }
        ],
        [
         { "params": [ "active_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "active" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Table panel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_esxhostname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "limit": "1",
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "MEM Usage",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "limit": "1",
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Gauge panel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MEM Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_esxhostname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Bar gauge panel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "MEM Usage",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_esxhostname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MEM Usage",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_esxhostname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_esxhostname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "limit": "1",
       "measurement": "vsphere_host_cpu",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Custom panels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datastore usage",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 41 },
     "format": "kbytes",
     "valueName": "current",
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "select": [
        [
         { "params": [ "capacity_latest" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "capacity" ], "type": "alias" }
        ],
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "used" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "dsname", "operator": "=", "value": "vsanDatastore" }
       ]
      }
     ]
    }
   ]
  }
 ]
}