{
 "title": "Proxmox Overview",
 "tags": [ "pve" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hosts",
    "label": "Hosts",
    "query": "show tag values with key = \"nodename\""
   },
   {
    "name": "vms",
    "label": "VMs",
    "query": "show tag values from system with key = \"host\" where vmid =~ /\\d+?/ and nodename =~/$hosts/"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpustat",
     "query": "SELECT sum(\"cpu\") FROM \"autogen\".\"cpustat\" WHERE (\"host\"::tag =~ /^$hosts$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "select sum(\"util\") from (SELECT (sum(\"memused\")*100 / sum(\"memtotal\")) as \"util\" FROM \"autogen\".\"memory\" WHERE (\"host\"::tag =~ /^$hosts$/) AND $timeFilter GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodename::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage local",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_nodename",
     "groupBy": [
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "measurement": "system",
     "query": "SELECT (\"used\"*100/\"total\") FROM \"autogen\".\"system\" WHERE (\"nodename\"::tag =~ /^$hosts$/ AND \"type\"::tag = 'dir') AND $timeFilter GROUP BY \"nodename\"",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "nodename::tag", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "type::tag", "operator": "=", "value": "lvmthin" }
     ]
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "nodename::tag" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ],
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" },
      { "condition": "AND", "key": "status::field", "operator": "=", "value": "running" }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type::tag" ], "type": "tag" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "nodename::tag", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "object::tag", "operator": "=", "value": "storages" }
     ]
    }
   ]
  },
  { "title": "Host Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Host utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_host",
     "measurement": "cpustat",
     "query": "SELECT \"cpu\" FROM \"autogen\".\"cpustat\" WHERE (\"host\"::tag =~ /^$hosts$/) AND $timeFilter GROUP BY host",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "measurement": "cpustat",
     "query": "SELECT (\"memused\"*100 / \"memtotal\") FROM \"autogen\".\"memory\" WHERE (\"host\"::tag =~ /^$hosts$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_nodename-$col",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "measurement": "blockstat",
     "query": "SELECT \"netin\", \"netout\" FROM \"autogen\".\"nics\" WHERE (\"host\"::tag =~ /^$hosts$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "rd_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "netin" ], "type": "alias" }
      ],
      [
       { "params": [ "wr_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "netout" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodename::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_nodename-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "measurement": "nics",
     "query": "SELECT \"netin\", \"netout\" FROM \"autogen\".\"nics\" WHERE (\"host\"::tag =~ /^$hosts$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "netin" ], "type": "alias" }
      ],
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "netout" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodename::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  { "title": "VM Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_host",
     "measurement": "system",
     "query": "SELECT \"cpu\" FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "measurement": "system",
     "query": "SELECT (\"mem\"*100/\"maxmem\") FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" }
     ]
    }
   ]
  },
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT non_negative_derivative(last(\"netin\"), 1s) FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter GROUP BY \"host\",time($__interval)",
     "select": [
      [
       { "params": [ "diskread" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT non_negative_derivative(last(\"netout\"), 1s) FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter GROUP BY \"host\",time($__interval)",
     "select": [
      [
       { "params": [ "diskread" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT non_negative_derivative(last(\"diskread\"), 1s) FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter GROUP BY \"host\",time($__interval)",
     "select": [
      [
       { "params": [ "diskread" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT non_negative_derivative(last(\"diskwrite\"), 1s) FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter GROUP BY \"host\",time($__interval)",
     "select": [
      [
       { "params": [ "diskread" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  }
 ]
}