{
 "title": "Proxmox Hosts",
 "tags": [ "pve" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hosts",
    "label": "Hosts",
    "query": "show tag values with key = \"nodename\""
   }
  ]
 },
 "panels": [
  { "title": "$hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hosts" },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "memtotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cpustat",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "memory",
     "query": "SELECT (\"memused\"*100/\"memtotal\") FROM \"autogen\".\"memory\" WHERE (\"host\"::tag =~ /^$hosts$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Local storage utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT (\"used\"*100/\"total\") FROM \"autogen\".\"system\" WHERE (\"nodename\"::tag =~ /^$hosts$/ AND \"type\"::tag = 'lvmthin') AND $timeFilter",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "nodename::tag", "operator": "=~", "value": "/^$hosts$/" },
      { "condition": "AND", "key": "type::tag", "operator": "=", "value": "lvmthin" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  { "title": "Host Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Host utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_host",
     "measurement": "cpustat",
     "query": "SELECT \"cpu\" FROM \"autogen\".\"cpustat\" WHERE (\"host\"::tag =~ /^$hosts$/) AND $timeFilter GROUP BY host",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "MEM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "measurement": "cpustat",
     "query": "SELECT (\"memused\"*100 / \"memtotal\") FROM \"autogen\".\"memory\" WHERE (\"host\"::tag =~ /^$hosts$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_nodename-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "measurement": "blockstat",
     "query": "SELECT \"netin\", \"netout\" FROM \"autogen\".\"nics\" WHERE (\"host\"::tag =~ /^$hosts$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "rd_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "netin" ], "type": "alias" }
      ],
      [
       { "params": [ "wr_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "netout" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodename::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_nodename-$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" }
     ],
     "measurement": "nics",
     "query": "SELECT \"netin\", \"netout\" FROM \"autogen\".\"nics\" WHERE (\"host\"::tag =~ /^$hosts$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "netin" ], "type": "alias" }
      ],
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "netout" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodename::tag", "operator": "=~", "value": "/^$hosts$/" }
     ]
    }
   ]
  }
 ]
}