{
 "title": "Proxmox VM",
 "tags": [ "pve" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hosts",
    "label": "Hosts",
    "query": "show tag values with key = \"nodename\""
   },
   {
    "name": "vms",
    "label": "VMs",
    "query": "show tag values from system with key = \"host\" where vmid =~ /\\d+?/ and nodename =~ /$hosts/"
   }
  ]
 },
 "panels": [
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT (\"status\")  FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT (\"mem\"*100/\"maxmem\")  FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "maxmem" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "ubuntu-4" }
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "maxmem" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT (\"status\")  FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" }
     ]
    }
   ]
  },
  {
   "title": "qemu version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT \"name\"  FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "running-qemu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" }
     ]
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "system",
     "query": "SELECT \"cpu\" FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "system",
     "query": "SELECT (\"mem\"*100/\"maxmem\") as mem FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT derivative(last(\"netin\"), 1s) FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter GROUP BY \"host\",time($__interval)",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "netin" ], "type": "alias" }
      ],
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "netout" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "system",
     "query": "SELECT derivative(last(\"diskwrite\"), 1s) FROM \"autogen\".\"system\" WHERE (\"host\"::tag =~ /^$vms$/) AND $timeFilter GROUP BY \"host\",time($__interval)",
     "select": [
      [
       { "params": [ "diskread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "diskread" ], "type": "alias" }
      ],
      [
       { "params": [ "diskwrite" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "diskwrite" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$vms$/" }
     ]
    }
   ]
  }
 ]
}