{
 "title": "vSAN Performance",
 "description": "Dashboard with vSAN performance data pulled from vCenter with Telegraf. The dashboard includes graphs with the same metrics as the built-in vSAN performance charts in vCenter ",
 "tags": [
  "vsphere",
  "vsan"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values from vsphere_vsan_summary with key = \"clustername\""
   },
   { "name": "interval", "query": "5m" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vCenter server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vcenter::tag" ], "type": "tag" }
     ],
     "measurement": "vsphere_vsan_performance_hostcpu",
     "select": [
      [
       { "params": [ "core_util_pct" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "clustername::tag" ], "type": "tag" }
     ],
     "measurement": "vsphere_vsan_performance_hostcpu",
     "select": [
      [
       { "params": [ "core_util_pct" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname::tag" ], "type": "tag" }
     ],
     "measurement": "vsphere_vsan_performance_hostcpu",
     "select": [
      [
       { "params": [ "core_util_pct" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vcenter::tag" ], "type": "tag" }
     ],
     "measurement": "vsphere_vsan_summary",
     "select": [
      [
       { "params": [ "overall_health" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=", "value": "cluster-03" }
     ]
    }
   ]
  },
  {
   "title": "Bytes to sync",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vsphere_vsan_summary",
     "select": [
      [
       { "params": [ "total_bytes_to_sync" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Backend IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "vsphere_vsan_performance_clusterdomcompmgr",
     "select": [
      [
       { "params": [ "iops_read" ], "type": "field" },
       { "params": [ "Read IOPS" ], "type": "alias" }
      ],
      [
       { "params": [ "iops_resync_read" ], "type": "field" },
       { "params": [ "Resync Read IOPS" ], "type": "alias" }
      ],
      [
       { "params": [ "iops_write" ], "type": "field" },
       { "params": [ "Write IOPS" ], "type": "alias" }
      ],
      [
       { "params": [ "iops_rec_write" ], "type": "field" },
       { "params": [ "Recovery Write IOPS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "vsphere_vsan_performance_clusterdomcompmgr",
     "select": [
      [
       { "params": [ "throughput_read" ], "type": "field" },
       { "params": [ "Read Throughput" ], "type": "alias" }
      ],
      [
       { "params": [ "tput_resync_read" ], "type": "field" },
       { "params": [ "Resync Read Throughput" ], "type": "alias" }
      ],
      [
       { "params": [ "throughput_write" ], "type": "field" },
       { "params": [ "Write Throughput" ], "type": "alias" }
      ],
      [
       { "params": [ "throughput_rec_write" ], "type": "field" },
       { "params": [ "Recovery Write Throughput" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "vsphere_vsan_performance_clusterdomcompmgr",
     "select": [
      [
       { "params": [ "latency_avg_read" ], "type": "field" },
       { "params": [ "Read Latency" ], "type": "alias" }
      ],
      [
       { "params": [ "lat_avg_resync_read" ], "type": "field" },
       { "params": [ "Resync Read Latency" ], "type": "alias" }
      ],
      [
       { "params": [ "latency_avg_write" ], "type": "field" },
       { "params": [ "Write Throughput" ], "type": "alias" }
      ],
      [
       { "params": [ "latency_avg_rec_write" ], "type": "field" },
       { "params": [ "Recovery Write Latency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Congestion",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "vsphere_vsan_performance_clusterdomcompmgr",
     "select": [
      [
       { "params": [ "congestion" ], "type": "field" },
       { "params": [ "Congestion" ], "type": "alias" }
      ],
      [
       { "params": [ "oio" ], "type": "field" },
       { "params": [ "Outstanding IO" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  { "title": "VM (frontend)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "VM IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "vsphere_vsan_performance_clusterdomclient",
     "select": [
      [
       { "params": [ "iops_read" ], "type": "field" },
       { "params": [ "Read IOPS" ], "type": "alias" }
      ],
      [
       { "params": [ "iops_write" ], "type": "field" },
       { "params": [ "Write IOPS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "VM Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "vsphere_vsan_performance_clusterdomclient",
     "select": [
      [
       { "params": [ "throughput_read" ], "type": "field" },
       { "params": [ "Read Throughput" ], "type": "alias" }
      ],
      [
       { "params": [ "throughput_write" ], "type": "field" },
       { "params": [ "Write Throughput" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "VM Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "vsphere_vsan_performance_clusterdomclient",
     "select": [
      [
       { "params": [ "latency_avg_read" ], "type": "field" },
       { "params": [ "Read Latency" ], "type": "alias" }
      ],
      [
       { "params": [ "latency_avg_write" ], "type": "field" },
       { "params": [ "Write Latency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "VM Congestion",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "vsphere_vsan_performance_clusterdomclient",
     "select": [
      [
       { "params": [ "congestion" ], "type": "field" },
       { "params": [ "Congestion" ], "type": "alias" }
      ],
      [
       { "params": [ "oio" ], "type": "field" },
       { "params": [ "Outstanding IO" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  }
 ]
}