{
 "title": "vSAN Capacity",
 "description": "Dashboard with vSAN capacity data pulled from vCenter with Telegraf",
 "tags": [
  "vsphere",
  "vsan"
 ],
 "time": { "from": "now-24h", "to": "now-5m" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "show tag values from vsphere_vsan_summary with key = \"clustername\""
   },
   { "name": "interval", "query": "30s" },
   { "name": "perf_interval", "query": "5m" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vCenter server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vcenter::tag" ], "type": "tag" }
     ],
     "measurement": "vsphere_vsan_performance_hostcpu",
     "select": [
      [
       { "params": [ "core_util_pct" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "clustername::tag" ], "type": "tag" }
     ],
     "measurement": "vsphere_vsan_performance_hostcpu",
     "select": [
      [
       { "params": [ "core_util_pct" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname::tag" ], "type": "tag" }
     ],
     "measurement": "vsphere_vsan_performance_hostcpu",
     "select": [
      [
       { "params": [ "core_util_pct" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vcenter::tag" ], "type": "tag" }
     ],
     "measurement": "vsphere_vsan_summary",
     "select": [
      [
       { "params": [ "overall_health" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=", "value": "cluster-03" }
     ]
    }
   ]
  },
  {
   "title": "Bytes to sync",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vsphere_vsan_summary",
     "select": [
      [
       { "params": [ "total_bytes_to_sync" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Total capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vsphere_vsan_summary",
     "select": [
      [
       { "params": [ "total_capacity_byte" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Free capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vsphere_vsan_summary",
     "select": [
      [
       { "params": [ "free_capacity_byte" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Compression saving",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vsphere_vsan_performance_vsanclustercapacity",
     "select": [
      [
       { "params": [ "saved_by_dedup" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Compression ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vsphere_vsan_performance_vsanclustercapacity",
     "select": [
      [
       { "params": [ "dedup_ratio" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Free capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vsphere_vsan_summary",
     "select": [
      [
       { "params": [ "total_capacity_byte" ], "type": "field" }
      ],
      [
       { "params": [ "free_capacity_byte" ], "type": "field" },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  { "title": "Capacity trend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Capacity trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "vsphere_vsan_summary",
     "select": [
      [
       { "params": [ "free_capacity_byte" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free_capacity" ], "type": "alias" }
      ],
      [
       { "params": [ "total_capacity_byte" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total_capacity" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Dedup savings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "vsphere_vsan_performance_vsanclustercapacity",
     "select": [
      [
       { "params": [ "saved_by_dedup" ], "type": "field" }
      ],
      [
       { "params": [ "dedup_ratio" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  { "title": "Resyncing objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Bytes to sync",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "vsphere_vsan_summary",
     "select": [
      [
       { "params": [ "total_bytes_to_sync" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Objects to sync",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "vsphere_vsan_summary",
     "select": [
      [
       { "params": [ "total_objects_to_sync" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovery ETA",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "vsphere_vsan_summary",
     "select": [
      [
       { "params": [ "total_recovery_eta" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "clustername::tag", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  }
 ]
}